name: Build

on: [push, pull_request]

jobs:
  tox:
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        # Need full history to determine version number.
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python packaging/test tools
      run: python -m pip install tox wheel
    - name: Show package version
      run: python setup.py --version
    - name: Test with tox
      run: tox
    - name: Build wheel
      run: python setup.py bdist_wheel
    - name: Upload wheels as artifacts
      uses: actions/upload-artifact@v4
      if: ${{ runner.os == 'Linux' && matrix.python-version == '3.9' }}
      with:
        name: python-packages
        path: |
          dist/*.whl
          dist/*.tar.gz
